# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_advanced', 'Can see prices and get writable offer file'), ('view_price', 'Can view prices')),
            },
        ),
    ]
