# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mconfig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.IntegerField()),
                ('registered', models.BooleanField()),
            ],
            options={
                'permissions': (('view_details', 'Can see price details'), ('view_price', 'Can view prices'), ('view_delivery', 'Can view delivery time'), ('register_users', 'Can add sales users')),
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='price_version',
            field=models.CharField(default='0.0', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='typecode',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mconfig.User'),
            preserve_default=False,
        ),
    ]
