# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mconfig', '0004_profile_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('view_details', 'Can see price details'), ('view_price', 'Can view prices'), ('view_delivery', 'Can view delivery time'), ('register_users', 'Can add sales users'), ('test', 'Test permission'))},
        ),
    ]
