# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mconfig', '0006_auto_20161213_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('view_all_orders', 'Can see order list'), ('view_details', 'Can see price details'), ('view_price', 'Can view prices'), ('view_delivery', 'Can view delivery time'))},
        ),
    ]
